#!/bin/sh

#This file is sourced from /etc/X11/Xsession.d/40x11-common_xsessionrc 
#at startup. It can be used to set environment variables for all applications.

#This file is sourced using /bin/sh, do not use bashisms!

#See: https://wiki.ubuntu.com/X/Config/SessionStartup

