#!/bin/sh

#This file is sourced from /etc/X11/Xsession.d/40x11-common_xsessionrc 
#at startup. It can be used to set environment variables for all applications.

#This file is sourced using /bin/sh, do not use bashisms!

#See: https://wiki.ubuntu.com/X/Config/SessionStartup

#disable menu key
xmodmap -e 'keycode 135 = NoSymbol'

# wyłączenie niełamiącej spacji na Alt+Spacja
# https://stackoverflow.com/questions/31383074/how-to-disable-non-breaking-space-with-altgrspace
setxkbmap -option "nbsp:none"

# Enable mouse keys (moving the mouse cursor by pressing keys on the numpad):
xkbset mousekeys
# and set its speed - modified settings from https://askubuntu.com/a/499037
xkbset mousekeysaccel 60 10 20 20 3

xhost +SI:localuser:hidden
xhost +SI:localuser:workrave_user
xhost +SI:localuser:root
